### ISSUE TITLE
set up actual task tracking

### ISSUE THREAD

**Issue by arcnmx** [arcnmx/arcnmx#14]
- [ ] pomodoro, reminders!!!
- [ ] actual schedule setup and usage
- [ ] track daily routine (separately?)
- [ ] track long-term goals
- [ ] ability to snooze/delay tasks for later follow-up
    - [ ] https://github.com/arcnmx/arcnmx/issues/66 for example
    - pre-order emails, shipments, etc
